replicaCount: 1

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 128Mi

# BEGIN AZURE PIPELINES MANAGED IMAGE
image:
  repository: devopse2e.azurecr.io/frontend
  tag: "e56468f29da6802404455aa9dd210ac18570b9cb"
appVersion: "e56468f29da6802404455aa9dd210ac18570b9cb"
# END AZURE PIPELINES MANAGED IMAGE
