replicaCount: 1

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 128Mi

# BEGIN AZURE PIPELINES MANAGED IMAGE
image:
  repository: devopse2e.azurecr.io/frontend
  tag: "candidate-b5f6bd7bfe4654a0feb0a7bb5ce54ade399630dd"
appVersion: "candidate-b5f6bd7bfe4654a0feb0a7bb5ce54ade399630dd"
# END AZURE PIPELINES MANAGED IMAGE
