replicaCount: 1

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 128Mi

# BEGIN AZURE PIPELINES MANAGED IMAGE
image:
  repository: devopse2e.azurecr.io/frontend
  tag: "candidate-882c983dccb1572ddc86c6a4fa6848807be5b4f5"
appVersion: "candidate-882c983dccb1572ddc86c6a4fa6848807be5b4f5"
# END AZURE PIPELINES MANAGED IMAGE
