replicaCount: 1

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

# BEGIN AZURE PIPELINES MANAGED IMAGE
image:
  repository: devopse2e.azurecr.io/catalog-service
  tag: "678d441fa6b798bc32bb9ab54ecf6434e87c040e"
appVersion: "678d441fa6b798bc32bb9ab54ecf6434e87c040e"
# END AZURE PIPELINES MANAGED IMAGE
