replicaCount: 1

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

# BEGIN AZURE PIPELINES MANAGED IMAGE
image:
  repository: devopse2e.azurecr.io/catalog-service
  tag: "f6ae043c99e509e138b37ac080a46eb79a1d1e03"
appVersion: "f6ae043c99e509e138b37ac080a46eb79a1d1e03"
# END AZURE PIPELINES MANAGED IMAGE
