replicaCount: 1

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

# BEGIN AZURE PIPELINES MANAGED IMAGE
image:
  repository: devopse2e.azurecr.io/catalog-service
  tag: "0ca60f6ba51294a4da29bcf48dc71e80f0c08824"
appVersion: "0ca60f6ba51294a4da29bcf48dc71e80f0c08824"
# END AZURE PIPELINES MANAGED IMAGE
