replicaCount: 2

service:
  type: NodePort
  nodePort: 30182

resources:
  requests:
    cpu: 200m
    memory: 192Mi
  limits:
    cpu: 750m
    memory: 384Mi

# BEGIN AZURE PIPELINES MANAGED IMAGE
image:
  repository: devopse2e.azurecr.io/catalog-service
  tag: "v4.0.4"
appVersion: "v4.0.4"
# END AZURE PIPELINES MANAGED IMAGE
