replicaCount: 2

image:
  repository: example.azurecr.io/api-gateway
  tag: "1.0.0"
  pullPolicy: IfNotPresent

appVersion: "1.0.0"
nameOverride: ""
fullnameOverride: "api-gateway"

containerPort: 8080

service:
  type: LoadBalancer
  port: 80
  annotations: {}
  loadBalancerIP: ""

health:
  path: /health/api-gateway
  readinessInitialDelaySeconds: 3
  livenessInitialDelaySeconds: 10

podAnnotations: {}
env:
  - name: PORT
    value: "8080"
  - name: FRONTEND_URL
    value: "http://frontend:80"
  - name: USER_SERVICE_URL
    value: "http://user-service:8081"
  - name: CATALOG_SERVICE_URL
    value: "http://catalog-service:8082"
  - name: ORDER_SERVICE_URL
    value: "http://order-service:8083"

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  seccompProfile:
    type: RuntimeDefault
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 128Mi

nodeSelector: {}
tolerations: []
affinity: {}
