replicaCount: 1

service:
  type: NodePort
  nodePort: 30090

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 128Mi

# BEGIN AZURE PIPELINES MANAGED IMAGE
image:
  repository: devopse2e.azurecr.io/api-gateway
  tag: "8f2bd12aed7f96bd50b62c22e5e9df8f4bd9be2b"
appVersion: "8f2bd12aed7f96bd50b62c22e5e9df8f4bd9be2b"
# END AZURE PIPELINES MANAGED IMAGE
