replicaCount: 2

service:
  type: LoadBalancer

resources:
  requests:
    cpu: 100m
    memory: 96Mi
  limits:
    cpu: 500m
    memory: 192Mi

# BEGIN AZURE PIPELINES MANAGED IMAGE
image:
  repository: devopse2e.azurecr.io/api-gateway
  tag: "v2.0.1"
appVersion: "v2.0.1"
# END AZURE PIPELINES MANAGED IMAGE
