replicaCount: 1

service:
  type: LoadBalancer

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 128Mi

# BEGIN AZURE PIPELINES MANAGED IMAGE
image:
  repository: devopse2e.azurecr.io/api-gateway
  tag: "candidate-fcd33107dcdb38f31d6588575418ec06d19756ae"
appVersion: "candidate-fcd33107dcdb38f31d6588575418ec06d19756ae"
# END AZURE PIPELINES MANAGED IMAGE
