replicaCount: 1

service:
  type: NodePort
  nodePort: 30090

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 128Mi

# BEGIN AZURE PIPELINES MANAGED IMAGE
image:
  repository: devopse2e.azurecr.io/api-gateway
  tag: "4bfa5f09a897e29758e8811c553faa1bdd4160ba"
appVersion: "4bfa5f09a897e29758e8811c553faa1bdd4160ba"
# END AZURE PIPELINES MANAGED IMAGE
