replicaCount: 1

resources:
  requests:
    cpu: 200m
    memory: 384Mi
  limits:
    cpu: 750m
    memory: 768Mi

# BEGIN AZURE PIPELINES MANAGED IMAGE
image:
  repository: devopse2e.azurecr.io/order-service
  tag: "candidate-be0efc29363fedae7483b34bebdee800618941af"
appVersion: "candidate-be0efc29363fedae7483b34bebdee800618941af"
# END AZURE PIPELINES MANAGED IMAGE
