replicaCount: 1

resources:
  requests:
    cpu: 200m
    memory: 384Mi
  limits:
    cpu: 750m
    memory: 768Mi

# BEGIN AZURE PIPELINES MANAGED IMAGE
image:
  repository: devopse2e.azurecr.io/order-service
  tag: "0f1630077ef130fbb00af4e68128212e90e1396c"
appVersion: "0f1630077ef130fbb00af4e68128212e90e1396c"
# END AZURE PIPELINES MANAGED IMAGE
