replicaCount: 1

resources:
  requests:
    cpu: 200m
    memory: 384Mi
  limits:
    cpu: 750m
    memory: 768Mi

# BEGIN AZURE PIPELINES MANAGED IMAGE
image:
  repository: devopse2e.azurecr.io/order-service
  tag: "a320cacaad9f6f3c51920dee78f34a3344660b47"
appVersion: "a320cacaad9f6f3c51920dee78f34a3344660b47"
# END AZURE PIPELINES MANAGED IMAGE
