parameters:
- name: serviceName
  type: string
- name: qualitySteps
  type: stepList
  default: []

stages:
- stage: CI
  displayName: 'CI - ${{ parameters.serviceName }}'
  jobs:
  - template: ../jobs/quality.yml
    parameters:
      serviceName: ${{ parameters.serviceName }}
      qualitySteps: ${{ parameters.qualitySteps }}
