name: system-e2e_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
      - '*'

pr:
  branches:
    include:
      - '*'

resources:
  pipelines:
    - pipeline: frontendCi
      source: 'frontend ci'
      trigger:
        branches:
          include:
            - main
        stages:
          - CI
    - pipeline: userServiceCi
      source: 'user-service ci'
      trigger:
        branches:
          include:
            - main
        stages:
          - CI
    - pipeline: catalogServiceCi
      source: 'catalog-service ci'
      trigger:
        branches:
          include:
            - main
        stages:
          - CI
    - pipeline: orderServiceCi
      source: 'order-service ci'
      trigger:
        branches:
          include:
            - main
        stages:
          - CI
    - pipeline: apiGatewayCi
      source: 'api-gateway ci'
      trigger:
        branches:
          include:
            - main
        stages:
          - CI
  repositories:
    - repository: frontend
      type: github
      endpoint: github.com_Azure-DevOps-E2E
      name: Azure-DevOps-E2E/frontend
      ref: refs/heads/main
    - repository: userService
      type: github
      endpoint: github.com_Azure-DevOps-E2E
      name: Azure-DevOps-E2E/user-service
      ref: refs/heads/main
    - repository: catalogService
      type: github
      endpoint: github.com_Azure-DevOps-E2E
      name: Azure-DevOps-E2E/catalog-service
      ref: refs/heads/main
    - repository: orderService
      type: github
      endpoint: github.com_Azure-DevOps-E2E
      name: Azure-DevOps-E2E/order-service
      ref: refs/heads/main
    - repository: apiGateway
      type: github
      endpoint: github.com_Azure-DevOps-E2E
      name: Azure-DevOps-E2E/api-gateway
      ref: refs/heads/main

pool:
  name: azure-agent

extends:
  template: templates/pipeline-contract.yml
  parameters:
    pipelineStages:
      - template: stages/e2e.yml@self
