stages:
- stage: CI
  displayName: 'CI - Checkout & Install Dependencies'
  jobs:
  - job: CI
    displayName: 'Install Python Dependencies'
    steps:
    - checkout: self
      displayName: 'Checkout source code'

    - task: UsePythonVersion@0
      displayName: 'Setup Python'
      inputs:
        versionSpec: '$(pythonVersion)'

    - script: |
        python --version
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      displayName: 'Install Python dependencies'

    - script: |
        python -m compileall .
      displayName: 'Validate Python code'
