replicaCount: 1

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 128Mi

# BEGIN AZURE PIPELINES MANAGED IMAGE
image:
  repository: devopse2e.azurecr.io/user-service
  tag: "024ef6762a869937f9db4ea0c111486382e62852"
appVersion: "024ef6762a869937f9db4ea0c111486382e62852"
# END AZURE PIPELINES MANAGED IMAGE
