replicaCount: 1

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 128Mi

# BEGIN AZURE PIPELINES MANAGED IMAGE
image:
  repository: devopse2e.azurecr.io/user-service
  tag: "candidate-7de32ce820bb4742a400100c9f91177ffe9d7902"
appVersion: "candidate-7de32ce820bb4742a400100c9f91177ffe9d7902"
# END AZURE PIPELINES MANAGED IMAGE
