replicaCount: 1

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 128Mi

# BEGIN AZURE PIPELINES MANAGED IMAGE
image:
  repository: devopse2e.azurecr.io/user-service
  tag: "2d23c4c0a12858d9b6ecd740ddb378d5f5f61edc"
appVersion: "2d23c4c0a12858d9b6ecd740ddb378d5f5f61edc"
# END AZURE PIPELINES MANAGED IMAGE
